name: scli
description: >
  A command line application for StackOverflow. We can call it - "StackOverflow
  under your fingers"
version: 1.0.0
homepage: https://github.com/theiskaa/stackoverflow_cli

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.1.1
  coverage: ^1.0.3
  dio: ^4.0.0
  io: ^1.0.0
  mockito: ^5.0.10

dev_dependencies:
  path: ^1.7.0
  http_mock_adapter: ^0.2.1
  pedantic: ^1.9.0
  test: ^1.17.7

executables:
  scli:
