name: scli
description: >
  A command line application for StackOverflow. We can call it - "StackOverflow
  under your fingers"
version: 1.0.0
homepage: https://github.com/theiskaa/stackoverflow_cli

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.1.1
  dio: ^4.0.0
  io: ^1.0.0
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0

executables:
  scli:
